#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/tests/assert.sh"

skill_text="$(cat "$ROOT/skills/adl/SKILL.md")"
connect_skill_text="$(cat "$ROOT/skills/adl-connect/SKILL.md")"
claude_skill_text="$(cat "$ROOT/skills-claude/adl/SKILL.md")"
claude_connect_skill_text="$(cat "$ROOT/skills-claude/adl-connect/SKILL.md")"

assert_contains "$skill_text" "adl architect reconnect" "Architect skill should document reconnect command"
assert_contains "$skill_text" "\$adl reconnect" "Architect skill should document skill-level reconnect invocation"
assert_contains "$skill_text" "ADL is ready. Connect Dev with \$adl-connect <pin>, then I will send the first handoff." "Architect skill should wait for Dev before first handoff"
assert_contains "$skill_text" "unless the user explicitly asks to queue a pending handoff" "Architect skill should preserve explicit pending-handoff override"
assert_contains "$skill_text" ".adl/staging/" "Architect skill should use staging for handoff preparation"
assert_contains "$skill_text" "ADL is always invoked for a goal" "Architect skill should define ADL as goal-directed"
assert_contains "$skill_text" "\`Goal\`" "Architect handoff should require goal context"
assert_contains "$skill_text" "\`Slice\`" "Architect handoff should require vertical slice context"
assert_contains "$skill_text" "Goal Alignment Review" "Architect review should require goal alignment"
assert_contains "$skill_text" "off-goal, product-wrong" "Architect review should reject technically correct but goal-wrong work"
assert_contains "$skill_text" "newest user feedback first" "Architect review should prioritize latest user feedback"
assert_contains "$skill_text" "If acceptance depends on rendered UX" "Architect review should scope rendered UX verification to UX-dependent slices"
assert_contains "$skill_text" "why rendered acceptance is not required" "Architect review should explain when rendered verification is skipped"
assert_contains "$connect_skill_text" "After a successful connection, ADL notifies Architect that Dev is connected and ready." "Dev connect skill should document architect ready notification"
assert_contains "$connect_skill_text" "wait for the first" "Dev connect skill should tell Dev to wait for first handoff"
assert_contains "$claude_skill_text" "Claude Code" "Claude Architect skill should name Claude Code"
assert_contains "$claude_skill_text" "/Users/liadgoren/.claude/skills/adl/scripts/adl" "Claude Architect skill should use Claude CLI path"
assert_contains "$claude_skill_text" "ADL is always invoked for a goal" "Claude Architect skill should define ADL as goal-directed"
assert_contains "$claude_skill_text" "Goal Alignment Review" "Claude Architect review should require goal alignment"
assert_contains "$claude_skill_text" "newest user feedback first" "Claude Architect review should prioritize latest user feedback"
assert_contains "$claude_skill_text" "If acceptance depends on rendered UX" "Claude Architect review should scope rendered UX verification to UX-dependent slices"
assert_contains "$claude_connect_skill_text" "Claude Code" "Claude Dev connect skill should name Claude Code"
assert_contains "$claude_connect_skill_text" "/Users/liadgoren/.claude/skills/adl/scripts/adl" "Claude Dev connect skill should use Claude CLI path"
