#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/tests/assert.sh"

skill_text="$(cat "$ROOT/skills/adl/SKILL.md")"
reset_skill_text="$(cat "$ROOT/skills/adl-reset/SKILL.md")"
connect_skill_text="$(cat "$ROOT/skills/adl-connect/SKILL.md")"
claude_skill_text="$(cat "$ROOT/skills-claude/adl/SKILL.md")"
claude_reset_skill_text="$(cat "$ROOT/skills-claude/adl-reset/SKILL.md")"
claude_connect_skill_text="$(cat "$ROOT/skills-claude/adl-connect/SKILL.md")"
commission_skill_text="$(cat "$ROOT/skills/commission/SKILL.md")"
commission_connect_skill_text="$(cat "$ROOT/skills/commission-connect/SKILL.md")"
commission_reset_skill_text="$(cat "$ROOT/skills/commission-reset/SKILL.md")"
claude_commission_skill_text="$(cat "$ROOT/skills-claude/commission/SKILL.md")"
claude_commission_connect_skill_text="$(cat "$ROOT/skills-claude/commission-connect/SKILL.md")"
claude_commission_reset_skill_text="$(cat "$ROOT/skills-claude/commission-reset/SKILL.md")"
all_skill_text="$skill_text
$reset_skill_text
$connect_skill_text
$claude_skill_text
$claude_reset_skill_text
$claude_connect_skill_text
$commission_skill_text
$commission_connect_skill_text
$commission_reset_skill_text
$claude_commission_skill_text
$claude_commission_connect_skill_text
$claude_commission_reset_skill_text"

assert_not_contains "$all_skill_text" "/Users/liadgoren/.codex/skills" "source skill templates should not contain maintainer-local Codex paths"
assert_not_contains "$all_skill_text" "/Users/liadgoren/.claude/skills" "source skill templates should not contain maintainer-local Claude paths"
assert_contains "$skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Codex Architect template should use install path token"
assert_contains "$connect_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl dev connect <pin>" "Codex connect template should use install path token"
assert_contains "$reset_skill_text" '{{ADL_SKILLS_DIR}}/adl-reset/scripts/adl-reset "$PWD/.adl"' "Codex reset template should use install path token"

assert_contains "$skill_text" "adl architect resume" "Architect skill should document resume command"
assert_contains "$skill_text" "adl architect refresh" "Architect skill should document refresh command"
assert_contains "$skill_text" "\$adl resume" "Architect skill should document skill-level resume invocation"
assert_contains "$skill_text" "\$adl refresh" "Architect skill should document skill-level refresh invocation"
assert_contains "$skill_text" "ADL is ready. Connect Dev with \$adl-connect 123456, then I will send the first handoff." "Architect skill should tell Architect to substitute the real pin"
assert_contains "$skill_text" "unless the user explicitly asks to queue a pending handoff" "Architect skill should preserve explicit pending-handoff override"
assert_contains "$skill_text" "run this \`send-dev\` command with escalation/outside-sandbox access" "Codex Architect skill should require outside-sandbox Ghostty handoff sends"
assert_contains "$skill_text" "Do not ask Dev to reconnect for this error" "Codex Architect skill should not misdiagnose sandbox Ghostty failures as Dev disconnects"
assert_contains "$skill_text" ".adl/staging/" "Architect skill should use staging for handoff preparation"
assert_contains "$skill_text" "ADL is a protocol layer for goal-directed work" "Architect skill should define ADL as a protocol layer"
assert_contains "$skill_text" "any upstream operator or agent workflow" "Architect skill should accept existing operator workflows"
assert_contains "$skill_text" "Preserve that workflow instead of replacing it" "Architect skill should preserve upstream planning style"
assert_contains "$skill_text" "ADL's main process opinion is the slice loop" "Architect skill should frame slice planning as ADL's process opinion"
assert_contains "$skill_text" "one scoped task after another" "Architect skill should define the slice loop"
assert_contains "$skill_text" "\`Goal\`" "Architect handoff should require goal context"
assert_contains "$skill_text" "\`Slice\`" "Architect handoff should require vertical slice context"
assert_contains "$skill_text" "protocol review" "Architect review should stay at the protocol level"
assert_contains "$skill_text" "approved-context match" "Architect review should verify approved context"
assert_contains "$skill_text" "Check goal match" "Architect review should verify goal"
assert_contains "$skill_text" "Check slice match" "Architect review should verify slice"
assert_contains "$skill_text" "handoff boundaries" "Architect review should verify boundaries"
assert_contains "$skill_text" "Check technical evidence" "Architect review should verify evidence"
assert_contains "$skill_text" "verify each acceptance criterion" "Architect review should verify acceptance criteria"
assert_contains "$skill_text" "Write only a short decision record" "Architect review should keep durable output terse"
assert_contains "$skill_text" "Verdict: Accepted | Accepted with notes | Pass this back to the Dev | Blocked" "Architect review should require compact verdict output"
assert_contains "$skill_text" "Checked: report, files/diffs, focused commands, acceptance criteria" "Architect review should require compact checked summary"
assert_contains "$skill_text" "Notes: only blockers, unverified items, or non-blocking concerns" "Architect review should require compact notes"
assert_contains "$skill_text" "Next: goal complete | continue with next handoff | awaiting user" "Architect review should require compact next action"
assert_contains "$skill_text" "the decision record is only the durable outcome" "Architect review should separate process from stored artifact"
assert_not_contains "$skill_text" "Goal/Slice Reviewed:" "Architect review should not require verbose goal/slice restatement"
assert_not_contains "$skill_text" "Approved Context Checked:" "Architect review should not require verbose approved-context restatement"
assert_not_contains "$skill_text" "Evidence Checked:" "Architect review should not require verbose evidence restatement"
assert_not_contains "$skill_text" "Acceptance Result:" "Architect review should not require verbose acceptance result restatement"
assert_not_contains "$skill_text" "Follow-up:" "Architect review should not require verbose follow-up restatement"
assert_contains "$skill_text" "newest user feedback first" "Architect review should prioritize latest user feedback"
assert_contains "$skill_text" "Do not accept if any acceptance criterion is \`FAIL\` or unexplained \`NOT VERIFIED\`" "Architect review should block failed or unexplained acceptance criteria"
assert_contains "$connect_skill_text" "After a successful connection, ADL notifies Architect that Dev is connected and ready." "Dev connect skill should document architect ready notification"
assert_contains "$connect_skill_text" "Pending Architect's Request: <path>" "Dev connect skill should tell Dev how to handle queued handoffs"
assert_contains "$connect_skill_text" "## Acceptance Results" "Dev connect skill should require acceptance-shaped reports"
assert_contains "$connect_skill_text" "Work autonomously inside the handoff boundaries" "Dev connect skill should preserve Dev autonomy inside scope"
assert_contains "$reset_skill_text" 'When invoked as `$adl-reset`' "ADL reset skill should document codex invocation"
assert_contains "$reset_skill_text" '{{ADL_SKILLS_DIR}}/adl-reset/scripts/adl-reset "$PWD/.adl"' "ADL reset skill should pass cwd .adl to reset script"
assert_contains "$reset_skill_text" "not as a project artifact" "ADL reset skill should frame .adl as protocol state"
assert_contains "$claude_skill_text" "Claude Code" "Claude Architect skill should name Claude Code"
assert_contains "$claude_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Claude Architect skill should use install path token"
assert_contains "$claude_skill_text" "/adl resume" "Claude Architect skill should use slash resume invocation language"
assert_contains "$claude_skill_text" "/adl refresh" "Claude Architect skill should use slash refresh invocation language"
assert_contains "$claude_skill_text" "Connect Dev with /adl-connect 123456" "Claude Architect skill should tell users to connect with slash skill and real pin"
assert_contains "$claude_skill_text" "Run this \`send-dev\` command with local Ghostty automation access" "Claude Architect skill should require local Ghostty automation for handoff sends"
assert_contains "$claude_skill_text" "Do not ask Dev to reconnect for this error" "Claude Architect skill should not misdiagnose Ghostty automation failures as Dev disconnects"
assert_not_contains "$claude_skill_text" "Connect Dev with \$adl-connect <pin>" "Claude Architect skill should not use Codex dollar skill language"
assert_not_contains "$claude_skill_text" 'Normal $adl resume' "Claude Architect skill should not use Codex dollar resume language"
assert_contains "$claude_skill_text" "ADL is a protocol layer for goal-directed work" "Claude Architect skill should define ADL as a protocol layer"
assert_contains "$claude_skill_text" "any upstream operator or agent workflow" "Claude Architect skill should accept existing operator workflows"
assert_contains "$claude_skill_text" "Preserve that workflow instead of replacing it" "Claude Architect skill should preserve upstream planning style"
assert_contains "$claude_skill_text" "ADL's main process opinion is the slice loop" "Claude Architect skill should frame slice planning as ADL's process opinion"
assert_contains "$claude_skill_text" "protocol review" "Claude Architect review should stay at the protocol level"
assert_contains "$claude_skill_text" "Check goal match" "Claude Architect review should verify goal"
assert_contains "$claude_skill_text" "Check slice match" "Claude Architect review should verify slice"
assert_contains "$claude_skill_text" "approved-context match" "Claude Architect review should verify approved context"
assert_contains "$claude_skill_text" "handoff boundaries" "Claude Architect review should verify boundaries"
assert_contains "$claude_skill_text" "Check technical evidence" "Claude Architect review should verify evidence"
assert_contains "$claude_skill_text" "verify each acceptance criterion" "Claude Architect review should verify acceptance criteria"
assert_contains "$claude_skill_text" "Write only a short decision record" "Claude Architect review should keep durable output terse"
assert_contains "$claude_skill_text" "Verdict: Accepted | Accepted with notes | Pass this back to the Dev | Blocked" "Claude Architect review should require compact verdict output"
assert_contains "$claude_skill_text" "Checked: report, files/diffs, focused commands, acceptance criteria" "Claude Architect review should require compact checked summary"
assert_contains "$claude_skill_text" "Notes: only blockers, unverified items, or non-blocking concerns" "Claude Architect review should require compact notes"
assert_contains "$claude_skill_text" "Next: goal complete | continue with next handoff | awaiting user" "Claude Architect review should require compact next action"
assert_contains "$claude_skill_text" "the decision record is only the durable outcome" "Claude Architect review should separate process from stored artifact"
assert_not_contains "$claude_skill_text" "Goal/Slice Reviewed:" "Claude Architect review should not require verbose goal/slice restatement"
assert_not_contains "$claude_skill_text" "Approved Context Checked:" "Claude Architect review should not require verbose approved-context restatement"
assert_not_contains "$claude_skill_text" "Evidence Checked:" "Claude Architect review should not require verbose evidence restatement"
assert_not_contains "$claude_skill_text" "Acceptance Result:" "Claude Architect review should not require verbose acceptance result restatement"
assert_not_contains "$claude_skill_text" "Follow-up:" "Claude Architect review should not require verbose follow-up restatement"
assert_contains "$claude_skill_text" "newest user feedback first" "Claude Architect review should prioritize latest user feedback"
assert_contains "$claude_connect_skill_text" "Pending Architect's Request: <path>" "Claude Dev connect skill should tell Dev how to handle queued handoffs"
assert_contains "$claude_connect_skill_text" "## Acceptance Results" "Claude Dev connect skill should require acceptance-shaped reports"
assert_contains "$claude_reset_skill_text" 'When invoked as `/adl-reset`' "Claude ADL reset skill should document slash invocation"
assert_contains "$claude_reset_skill_text" '{{ADL_SKILLS_DIR}}/adl-reset/scripts/adl-reset "$PWD/.adl"' "Claude ADL reset skill should pass cwd .adl to reset script"
assert_contains "$claude_reset_skill_text" "not as a project artifact" "Claude ADL reset skill should frame .adl as protocol state"
assert_contains "$claude_connect_skill_text" "Claude Code" "Claude Dev connect skill should name Claude Code"
assert_contains "$claude_connect_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Claude Dev connect skill should use install path token"
assert_contains "$claude_connect_skill_text" "When invoked as \`/adl-connect <pin>\`" "Claude Dev connect skill should use slash invocation language"
assert_not_contains "$claude_connect_skill_text" 'When invoked as `$adl-connect <pin>`' "Claude Dev connect skill should not use Codex dollar skill language"
assert_contains "$commission_skill_text" "{{ADL_SKILLS_DIR}}/commission/scripts/commission" "Codex Commission template should use install path token"
assert_contains "$commission_connect_skill_text" "use the printed \`Target repo\` as the authoritative repository" "Commission connect should make target repo authoritative"
assert_contains "$commission_connect_skill_text" "Consumer entry cwd is only a routing anchor" "Commission connect should describe entry cwd routing"
assert_contains "$commission_connect_skill_text" "according to that repo's own instructions and operating model" "Commission connect should preserve target repo operating model"
assert_contains "$commission_connect_skill_text" "does not decide whether the target repo expects direct implementation" "Commission connect should not default to direct implementation"
assert_contains "$commission_connect_skill_text" "orchestrator repo may require creating or updating a work card" "Commission connect should cover orchestrator repos without making them mandatory"
assert_not_contains "$commission_connect_skill_text" "implement only its scope in the target repo" "Commission connect should not tell Consumer to directly implement by default"
assert_contains "$commission_reset_skill_text" '{{ADL_SKILLS_DIR}}/commission-reset/scripts/commission-reset "$PWD/.commission"' "Commission reset should pass cwd .commission"
assert_contains "$claude_commission_skill_text" "/commission-connect <pin>" "Claude Commission skill should use slash connect language"
assert_contains "$claude_commission_connect_skill_text" "Claude Code" "Claude Commission connect should name Claude Code"
assert_contains "$claude_commission_connect_skill_text" "according to that repo's own instructions and operating model" "Claude Commission connect should preserve target repo operating model"
assert_not_contains "$claude_commission_connect_skill_text" "implement only its scope in the target repo" "Claude Commission connect should not tell Consumer to directly implement by default"
assert_contains "$claude_commission_reset_skill_text" 'When invoked as `/commission-reset`' "Claude Commission reset should use slash invocation"
