#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/tests/assert.sh"

skill_text="$(cat "$ROOT/skills/adl/SKILL.md")"
clear_skill_text="$(cat "$ROOT/skills/adl-clear/SKILL.md")"
connect_skill_text="$(cat "$ROOT/skills/adl-connect/SKILL.md")"
claude_skill_text="$(cat "$ROOT/skills-claude/adl/SKILL.md")"
claude_clear_skill_text="$(cat "$ROOT/skills-claude/adl-clear/SKILL.md")"
claude_connect_skill_text="$(cat "$ROOT/skills-claude/adl-connect/SKILL.md")"
all_skill_text="$skill_text
$clear_skill_text
$connect_skill_text
$claude_skill_text
$claude_clear_skill_text
$claude_connect_skill_text"

assert_not_contains "$all_skill_text" "/Users/liadgoren/.codex/skills" "source skill templates should not contain maintainer-local Codex paths"
assert_not_contains "$all_skill_text" "/Users/liadgoren/.claude/skills" "source skill templates should not contain maintainer-local Claude paths"
assert_contains "$skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Codex Architect template should use install path token"
assert_contains "$connect_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl dev connect <pin>" "Codex connect template should use install path token"
assert_contains "$clear_skill_text" '{{ADL_SKILLS_DIR}}/adl-clear/scripts/adl-clear "$PWD/.adl"' "Codex clear template should use install path token"

assert_contains "$skill_text" "adl architect reconnect" "Architect skill should document reconnect command"
assert_contains "$skill_text" "\$adl reconnect" "Architect skill should document skill-level reconnect invocation"
assert_contains "$skill_text" "ADL is ready. Connect Dev with \$adl-connect 123456, then I will send the first handoff." "Architect skill should tell Architect to substitute the real pin"
assert_contains "$skill_text" "unless the user explicitly asks to queue a pending handoff" "Architect skill should preserve explicit pending-handoff override"
assert_contains "$skill_text" ".adl/staging/" "Architect skill should use staging for handoff preparation"
assert_contains "$skill_text" "ADL is a protocol layer for goal-directed work" "Architect skill should define ADL as a protocol layer"
assert_contains "$skill_text" "any upstream operator or agent workflow" "Architect skill should accept existing operator workflows"
assert_contains "$skill_text" "Preserve that workflow instead of replacing it" "Architect skill should preserve upstream planning style"
assert_contains "$skill_text" "ADL's main process opinion is the slice loop" "Architect skill should frame slice planning as ADL's process opinion"
assert_contains "$skill_text" "one scoped task after another" "Architect skill should define the slice loop"
assert_contains "$skill_text" "\`Goal\`" "Architect handoff should require goal context"
assert_contains "$skill_text" "\`Slice\`" "Architect handoff should require vertical slice context"
assert_contains "$skill_text" "protocol review" "Architect review should stay at the protocol level"
assert_contains "$skill_text" "approved-context match" "Architect review should verify approved context"
assert_contains "$skill_text" "Check goal match" "Architect review should verify goal"
assert_contains "$skill_text" "Check slice match" "Architect review should verify slice"
assert_contains "$skill_text" "handoff boundaries" "Architect review should verify boundaries"
assert_contains "$skill_text" "Check technical evidence" "Architect review should verify evidence"
assert_contains "$skill_text" "verify each acceptance criterion" "Architect review should verify acceptance criteria"
assert_contains "$skill_text" "Verdict: Accepted | Accepted with notes | Pass this back to the Dev | Blocked" "Architect review should require compact verdict output"
assert_contains "$skill_text" "newest user feedback first" "Architect review should prioritize latest user feedback"
assert_contains "$skill_text" "Do not accept if any acceptance criterion is \`FAIL\` or unexplained \`NOT VERIFIED\`" "Architect review should block failed or unexplained acceptance criteria"
assert_contains "$skill_text" "## Transport Capture Recovery" "Codex Architect skill should use generic transport recovery heading"
assert_contains "$skill_text" "selected ADL transport target" "Codex Architect skill should describe generic transport capture"
assert_contains "$skill_text" "role-specific session metadata" "Codex Architect skill should describe persisted role metadata"
assert_contains "$skill_text" "OS, terminal, adapter, terminal id, and human-readable label" "Codex Architect skill should list persisted transport metadata"
assert_contains "$skill_text" "transport configured during install or update" "Codex Architect skill should document installed transport config"
assert_contains "$skill_text" "ADL_TRANSPORT=auto\` remains available as an explicit diagnostic/setup helper, but it is not the default product path" "Codex Architect skill should not describe auto as default"
assert_contains "$skill_text" "ADL_TRANSPORT=ghostty-macos" "Codex Architect skill should document explicit Ghostty override"
assert_contains "$skill_text" "ADL_TRANSPORT=tmux" "Codex Architect skill should document explicit tmux override"
assert_contains "$skill_text" "ADL_TRANSPORT=terminal-macos" "Codex Architect skill should document explicit Terminal.app override"
assert_contains "$skill_text" "adl doctor transport architect" "Codex Architect skill should prefer generic transport doctor"
assert_contains "$skill_text" "adl doctor ghostty architect" "Codex Architect skill should retain Ghostty-specific doctor"
assert_contains "$skill_text" "uses AppleScript (\`ghostty-macos\` or \`terminal-macos\`)" "Codex Architect skill should scope AppleScript permission guidance to AppleScript adapters"
assert_not_contains "$skill_text" "capture the focused Ghostty pane" "Codex Architect skill should not describe generic capture as Ghostty-only"
assert_contains "$connect_skill_text" "After a successful connection, ADL notifies Architect that Dev is connected and ready." "Dev connect skill should document architect ready notification"
assert_contains "$connect_skill_text" "Pending Architect's Request: <path>" "Dev connect skill should tell Dev how to handle queued handoffs"
assert_contains "$connect_skill_text" "## Acceptance Results" "Dev connect skill should require acceptance-shaped reports"
assert_contains "$connect_skill_text" "Work autonomously inside the handoff boundaries" "Dev connect skill should preserve Dev autonomy inside scope"
assert_contains "$connect_skill_text" "## Transport Capture Recovery" "Codex Dev connect skill should use generic transport recovery heading"
assert_contains "$connect_skill_text" "selected ADL adapter" "Codex Dev connect skill should describe adapter-selected capture"
assert_contains "$connect_skill_text" "role-specific session metadata" "Codex Dev connect skill should describe persisted role metadata"
assert_contains "$connect_skill_text" "transport configured during install or update" "Codex Dev connect skill should document installed transport config"
assert_contains "$connect_skill_text" "ADL_TRANSPORT=auto\` remains available as an explicit diagnostic/setup helper, but it is not the default product path" "Codex Dev connect skill should not describe auto as default"
assert_contains "$connect_skill_text" "adl doctor transport dev" "Codex Dev connect skill should prefer generic transport doctor"
assert_contains "$connect_skill_text" "adl doctor ghostty dev" "Codex Dev connect skill should retain Ghostty-specific doctor"
assert_contains "$connect_skill_text" "uses AppleScript (\`ghostty-macos\` or \`terminal-macos\`)" "Codex Dev connect skill should scope AppleScript permission guidance to AppleScript adapters"
assert_not_contains "$connect_skill_text" "through Ghostty AppleScript" "Codex Dev connect skill should not describe generic connect as Ghostty-only"
assert_contains "$clear_skill_text" 'When invoked as `$adl-clear`' "ADL clear skill should document codex invocation"
assert_contains "$clear_skill_text" '{{ADL_SKILLS_DIR}}/adl-clear/scripts/adl-clear "$PWD/.adl"' "ADL clear skill should pass cwd .adl to clear script"
assert_contains "$clear_skill_text" "not as a project artifact" "ADL clear skill should frame .adl as protocol state"
assert_contains "$claude_skill_text" "Claude Code" "Claude Architect skill should name Claude Code"
assert_contains "$claude_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Claude Architect skill should use install path token"
assert_contains "$claude_skill_text" "/adl reconnect" "Claude Architect skill should use slash invocation language"
assert_contains "$claude_skill_text" "Connect Dev with /adl-connect 123456" "Claude Architect skill should tell users to connect with slash skill and real pin"
assert_not_contains "$claude_skill_text" "Connect Dev with \$adl-connect <pin>" "Claude Architect skill should not use Codex dollar skill language"
assert_not_contains "$claude_skill_text" 'Normal $adl resume' "Claude Architect skill should not use Codex dollar resume language"
assert_contains "$claude_skill_text" "ADL is a protocol layer for goal-directed work" "Claude Architect skill should define ADL as a protocol layer"
assert_contains "$claude_skill_text" "any upstream operator or agent workflow" "Claude Architect skill should accept existing operator workflows"
assert_contains "$claude_skill_text" "Preserve that workflow instead of replacing it" "Claude Architect skill should preserve upstream planning style"
assert_contains "$claude_skill_text" "ADL's main process opinion is the slice loop" "Claude Architect skill should frame slice planning as ADL's process opinion"
assert_contains "$claude_skill_text" "protocol review" "Claude Architect review should stay at the protocol level"
assert_contains "$claude_skill_text" "Check goal match" "Claude Architect review should verify goal"
assert_contains "$claude_skill_text" "Check slice match" "Claude Architect review should verify slice"
assert_contains "$claude_skill_text" "approved-context match" "Claude Architect review should verify approved context"
assert_contains "$claude_skill_text" "handoff boundaries" "Claude Architect review should verify boundaries"
assert_contains "$claude_skill_text" "Check technical evidence" "Claude Architect review should verify evidence"
assert_contains "$claude_skill_text" "verify each acceptance criterion" "Claude Architect review should verify acceptance criteria"
assert_contains "$claude_skill_text" "Verdict: Accepted | Accepted with notes | Pass this back to the Dev | Blocked" "Claude Architect review should require compact verdict output"
assert_contains "$claude_skill_text" "newest user feedback first" "Claude Architect review should prioritize latest user feedback"
assert_contains "$claude_skill_text" "## Transport Capture Recovery" "Claude Architect skill should use generic transport recovery heading"
assert_contains "$claude_skill_text" "selected ADL transport target" "Claude Architect skill should describe generic transport capture"
assert_contains "$claude_skill_text" "role-specific session metadata" "Claude Architect skill should describe persisted role metadata"
assert_contains "$claude_skill_text" "OS, terminal, adapter, terminal id, and human-readable label" "Claude Architect skill should list persisted transport metadata"
assert_contains "$claude_skill_text" "transport configured during install or update" "Claude Architect skill should document installed transport config"
assert_contains "$claude_skill_text" "ADL_TRANSPORT=auto\` remains available as an explicit diagnostic/setup helper, but it is not the default product path" "Claude Architect skill should not describe auto as default"
assert_contains "$claude_skill_text" "ADL_TRANSPORT=ghostty-macos" "Claude Architect skill should document explicit Ghostty override"
assert_contains "$claude_skill_text" "ADL_TRANSPORT=tmux" "Claude Architect skill should document explicit tmux override"
assert_contains "$claude_skill_text" "ADL_TRANSPORT=terminal-macos" "Claude Architect skill should document explicit Terminal.app override"
assert_contains "$claude_skill_text" "adl doctor transport architect" "Claude Architect skill should prefer generic transport doctor"
assert_contains "$claude_skill_text" "adl doctor ghostty architect" "Claude Architect skill should retain Ghostty-specific doctor"
assert_contains "$claude_skill_text" "uses AppleScript (\`ghostty-macos\` or \`terminal-macos\`)" "Claude Architect skill should scope AppleScript permission guidance to AppleScript adapters"
assert_not_contains "$claude_skill_text" "capture the focused Ghostty pane" "Claude Architect skill should not describe generic capture as Ghostty-only"
assert_contains "$claude_connect_skill_text" "Pending Architect's Request: <path>" "Claude Dev connect skill should tell Dev how to handle queued handoffs"
assert_contains "$claude_connect_skill_text" "## Acceptance Results" "Claude Dev connect skill should require acceptance-shaped reports"
assert_contains "$claude_connect_skill_text" "## Transport Capture Recovery" "Claude Dev connect skill should use generic transport recovery heading"
assert_contains "$claude_connect_skill_text" "selected ADL adapter" "Claude Dev connect skill should describe adapter-selected capture"
assert_contains "$claude_connect_skill_text" "role-specific session metadata" "Claude Dev connect skill should describe persisted role metadata"
assert_contains "$claude_connect_skill_text" "transport configured during install or update" "Claude Dev connect skill should document installed transport config"
assert_contains "$claude_connect_skill_text" "ADL_TRANSPORT=auto\` remains available as an explicit diagnostic/setup helper, but it is not the default product path" "Claude Dev connect skill should not describe auto as default"
assert_contains "$claude_connect_skill_text" "adl doctor transport dev" "Claude Dev connect skill should prefer generic transport doctor"
assert_contains "$claude_connect_skill_text" "adl doctor ghostty dev" "Claude Dev connect skill should retain Ghostty-specific doctor"
assert_contains "$claude_connect_skill_text" "uses AppleScript (\`ghostty-macos\` or \`terminal-macos\`)" "Claude Dev connect skill should scope AppleScript permission guidance to AppleScript adapters"
assert_not_contains "$claude_connect_skill_text" "through Ghostty AppleScript" "Claude Dev connect skill should not describe generic connect as Ghostty-only"
assert_contains "$claude_clear_skill_text" 'When invoked as `/adl-clear`' "Claude ADL clear skill should document slash invocation"
assert_contains "$claude_clear_skill_text" '{{ADL_SKILLS_DIR}}/adl-clear/scripts/adl-clear "$PWD/.adl"' "Claude ADL clear skill should pass cwd .adl to clear script"
assert_contains "$claude_clear_skill_text" "not as a project artifact" "Claude ADL clear skill should frame .adl as protocol state"
assert_contains "$claude_connect_skill_text" "Claude Code" "Claude Dev connect skill should name Claude Code"
assert_contains "$claude_connect_skill_text" "{{ADL_SKILLS_DIR}}/adl/scripts/adl" "Claude Dev connect skill should use install path token"
assert_contains "$claude_connect_skill_text" "When invoked as \`/adl-connect <pin>\`" "Claude Dev connect skill should use slash invocation language"
assert_not_contains "$claude_connect_skill_text" 'When invoked as `$adl-connect <pin>`' "Claude Dev connect skill should not use Codex dollar skill language"
